http.server: disambiguate http.server import
ganeti.http.server does two overlapping imports:

 import http.server  # from Python's standard library
 ...
 from ganeti import http

In Python 3, the second import shadows the first one causing breakage:

 File "/path/to/ganeti/ganeti/http/server.py", line 274, in HttpResponder
   responses = http.server.BaseHTTPRequestHandler.responses
 AttributeError: module 'ganeti.http' has no attribute 'server'

Since we are only using BaseHTTPRequestHandler from Python's
http.server, import it directly into the module's namespace, which also
fixes the issue.

Signed-off-by: Apollon Oikonomopoulos <apoikos@dmesg.gr>